name=TLE75080
version=1.0.1
author=Engeen
maintainer=Engeen <info@engeen.nl>
sentence=SPI driver for TLE75080
paragraph=Simple SPI driver for the TLE75080, a 16-channel high-side switch IC.
category=Signal Input/Output
url=https://github.com/engeen-nl/Arduino-TLE75080
architectures=samd
